let draft=null,source=null;const statusEl=document.getElementById('status'),educationEl=document.getElementById('education'),experienceEl=document.getElementById('experience');
function setStatus(text,type){statusEl.textContent=text;statusEl.className=type||'';}function getPath(o,p){return p.split('.').reduce((v,k)=>v?.[k],o);}function setPath(o,p,value){const parts=p.split('.');let t=o;for(let i=0;i<parts.length-1;i++){t[parts[i]]||={};t=t[parts[i]];}t[parts.at(-1)]=value;}function esc(v){return String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function educationItem(item={},index){const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="item-head"><strong>Education ${index+1}</strong><button class="danger remove">Remove</button></div><div class="grid"><label>Institution<input data-key="institution" value="${esc(item.institution)}"></label><label>Degree<input data-key="degree" value="${esc(item.degree)}"></label><label>Duration<input data-key="duration" value="${esc(item.duration)}"></label><label>Graduation year<input data-key="graduation_year" value="${esc(item.graduation_year)}"></label></div>`;d.querySelector('.remove').onclick=()=>{d.remove();renumber();};return d;}
function experienceItem(item={},index){const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="item-head"><strong>Experience ${index+1}</strong><button class="danger remove">Remove</button></div><div class="grid"><label>Company<input data-key="company" value="${esc(item.company)}"></label><label>Title<input data-key="title" value="${esc(item.title)}"></label><label>Period<input data-key="period" value="${esc(item.period)}"></label></div><label style="margin-top:10px">Description<textarea data-key="description">${esc(item.description)}</textarea></label>`;d.querySelector('.remove').onclick=()=>{d.remove();renumber();};return d;}
function renumber(){[...educationEl.children].forEach((n,i)=>n.querySelector('strong').textContent=`Education ${i+1}`);[...experienceEl.children].forEach((n,i)=>n.querySelector('strong').textContent=`Experience ${i+1}`);}
function render(){document.querySelectorAll('[data-path]').forEach(i=>i.value=getPath(draft,i.dataset.path)||'');document.getElementById('skills').value=(draft.skills||[]).join('\n');document.getElementById('achievements').value=(draft.profile_text?.achievements||[]).join('\n');educationEl.replaceChildren(...(draft.education||[]).map(educationItem));experienceEl.replaceChildren(...(draft.experience||[]).map(experienceItem));if(!educationEl.children.length)educationEl.appendChild(educationItem({},0));if(!experienceEl.children.length)experienceEl.appendChild(experienceItem({},0));document.getElementById('source').textContent=[source?.fileName,source?.format?.toUpperCase(),source?.textLength?`${source.textLength} extracted characters`:''].filter(Boolean).join(' · ');}
function collectItems(container,keys){return [...container.children].map(node=>{const item={};keys.forEach(k=>item[k]=node.querySelector(`[data-key="${k}"]`)?.value.trim()||'');return item;}).filter(item=>Object.values(item).some(Boolean));}
function collectDraft(){const next=structuredClone(draft);document.querySelectorAll('[data-path]').forEach(i=>setPath(next,i.dataset.path,i.value.trim()));next.skills=document.getElementById('skills').value.split(/[\n,]/).map(v=>v.trim()).filter(Boolean);next.profile_text||={};next.profile_text.achievements=document.getElementById('achievements').value.split('\n').map(v=>v.trim()).filter(Boolean);next.education=collectItems(educationEl,['institution','degree','duration','graduation_year']);next.experience=collectItems(experienceEl,['company','title','period','description']);return next;}
document.getElementById('addEducation').onclick=()=>educationEl.appendChild(educationItem({},educationEl.children.length));document.getElementById('addExperience').onclick=()=>experienceEl.appendChild(experienceItem({},experienceEl.children.length));document.getElementById('cancel').onclick=async()=>{await chrome.storage.local.remove(['resumeDraft','resumeSource']);window.close();};
document.getElementById('confirm').onclick=async e=>{const button=e.currentTarget;button.disabled=true;setStatus('Saving confirmed profile…','');try{const response=await fetch('http://127.0.0.1:8731/resume/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft:collectDraft()})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Profile save failed (${response.status}).`);await chrome.storage.local.remove(['resumeDraft','resumeSource']);setStatus(`Profile saved. ${payload.summary?.education||0} education, ${payload.summary?.experience||0} experience and ${payload.summary?.skills||0} skill entries are now available to AI-Filler.`,'ok');button.textContent='Saved ✓';}catch(error){setStatus(error.message||String(error),'error');button.disabled=false;}};
chrome.storage.local.get(['resumeDraft','resumeSource']).then(data=>{draft=data.resumeDraft;source=data.resumeSource;if(!draft){setStatus('No resume draft found. Return to the AI-Filler popup and import a resume first.','error');document.getElementById('confirm').disabled=true;return;}render();});
