'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { MAX_RESUME_BYTES, ResumeImportError, detectFormat, extractResumeText, mergeResumeDraft, sanitizeResumeDraft } = require('../lib/resume');
const { createEmptyProfile, validateProfile } = require('../lib/profile');
const usefulText = `Garv Jhajharia\nAI Engineer\ngarv@example.com\nBengaluru, India\n\nExperience\nExample Labs — AI Engineer — 2025 to Present\nBuilt applied AI systems for real customer workflows using Python, JavaScript, SQL, APIs, speech recognition, backend services, validation, testing, and deployment.\n\nEducation\nBMS Institute of Technology and Management — B.Tech Computer Science — 2026\n\nSkills\nPython JavaScript SQL Node.js React APIs Machine Learning`;
const b64 = value => Buffer.from(value).toString('base64');
function existingProfile() { const p=createEmptyProfile(); p.personal.full_name='Confirmed Name'; p.personal.primary_email='confirmed@example.com'; p.links.github='https://github.com/confirmed'; p.education=[{institution:'BMSIT',degree:'B.Tech CSE',duration:'',graduation_year:'2026',current_year_of_study:'',class_12_percentage:'',class_10_percentage:''}]; p.experience=[{company:'Old Co',title:'Intern',period:'2024',description:'Existing confirmed experience'}]; p.skills=['Python']; p.job_preferences.current_ctc='5 LPA'; p.documents.resume_path='C:/confirmed/resume.pdf'; p.learned_answers=[{question:'Why this role?',answer:'Confirmed answer'}]; p.custom={keep:true}; return p; }
test('detects supported formats and rejects unsupported input',()=>{assert.equal(detectFormat('resume.pdf',''),'pdf');assert.equal(detectFormat('resume.docx',''),'docx');assert.equal(detectFormat('resume.txt',''),'txt');assert.throws(()=>detectFormat('resume.doc','application/msword'),e=>e.code==='RESUME_FORMAT_UNSUPPORTED');});
test('extracts useful TXT natively',async()=>{const r=await extractResumeText({fileName:'resume.txt',mimeType:'text/plain',base64:b64(usefulText)});assert.equal(r.format,'txt');assert.match(r.text,/Garv Jhajharia/);});
test('extracts PDF and detects OCR-required sparse PDFs',async()=>{let destroyed=false;class GoodPDF{async getText(){return{text:usefulText}}async destroy(){destroyed=true}}const r=await extractResumeText({fileName:'resume.pdf',mimeType:'application/pdf',base64:b64('pdf')},{loaders:{PDFParse:GoodPDF}});assert.equal(r.format,'pdf');assert.equal(destroyed,true);class SparsePDF{async getText(){return{text:'Garv Jhajharia'}}async destroy(){}}await assert.rejects(()=>extractResumeText({fileName:'scan.pdf',mimeType:'application/pdf',base64:b64('pdf')},{loaders:{PDFParse:SparsePDF}}),e=>e instanceof ResumeImportError&&e.code==='RESUME_OCR_REQUIRED');});
test('extracts DOCX with Mammoth raw-text API',async()=>{const mammoth={async extractRawText({buffer}){assert.ok(Buffer.isBuffer(buffer));return{value:usefulText,messages:[{message:'warning'}]}}};const r=await extractResumeText({fileName:'resume.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',base64:b64('docx')},{loaders:{mammoth}});assert.deepEqual(r.warnings,['warning']);});
test('rejects oversized input before parsing',async()=>{const huge=Buffer.alloc(MAX_RESUME_BYTES+1,65).toString('base64');await assert.rejects(()=>extractResumeText({fileName:'resume.txt',mimeType:'text/plain',base64:huge}),e=>e.code==='RESUME_FILE_TOO_LARGE');});
test('sanitizes draft and strips preferences/local state',()=>{const d=sanitizeResumeDraft({personal:{full_name:' Jane Doe ',primary_email:'jane@example.com',location:{city:'Bengaluru'}},links:{github:'https://github.com/jane'},education:[{institution:'Uni',degree:'B.Tech',graduation_year:'2026'}],experience:[{company:'Co',title:'Engineer',period:'2025-present',description:'Worked on AI'}],skills:['Python','python','',7],job_preferences:{current_ctc:'999 LPA'},documents:{resume_path:'/invented/path.pdf'},learned_answers:[{question:'x',answer:'y'}],profile_text:{bio:'Factual bio',achievements:['Won X','won x']}});assert.equal(d.personal.full_name,'Jane Doe');assert.deepEqual(d.skills,['Python']);assert.equal(d.job_preferences.current_ctc,'');assert.equal(d.documents.resume_path,'');assert.deepEqual(d.learned_answers,[]);assert.deepEqual(validateProfile(d),[]);});
test('non-destructive merge preserves confirmed local state',()=>{const m=mergeResumeDraft(existingProfile(),{personal:{full_name:'Resume Name',primary_email:'resume@example.com',phone:'+91 12345',location:{city:'Bengaluru'}},links:{github:'https://github.com/resume',linkedin:'https://linkedin.com/in/resume'},current_employment:{company:'New Co',role:'AI Engineer',years_of_experience:'2 years'},education:[{institution:'BMSIT',degree:'B.Tech CSE',graduation_year:'2026'},{institution:'High School',degree:'12th',graduation_year:'2022'}],experience:[{company:'Old Co',title:'Intern',period:'2024',description:'duplicate'},{company:'New Co',title:'AI Engineer',period:'2025-present',description:'role'}],skills:['python','JavaScript'],profile_text:{bio:'Resume bio',achievements:['Achievement A']},job_preferences:{current_ctc:'999 LPA'}});assert.equal(m.personal.full_name,'Confirmed Name');assert.equal(m.personal.primary_email,'confirmed@example.com');assert.equal(m.personal.phone,'+91 12345');assert.equal(m.links.github,'https://github.com/confirmed');assert.equal(m.links.linkedin,'https://linkedin.com/in/resume');assert.equal(m.job_preferences.current_ctc,'5 LPA');assert.equal(m.documents.resume_path,'C:/confirmed/resume.pdf');assert.deepEqual(m.learned_answers,[{question:'Why this role?',answer:'Confirmed answer'}]);assert.deepEqual(m.custom,{keep:true});assert.equal(m.education.length,2);assert.equal(m.experience.length,2);assert.deepEqual(m.skills,['Python','JavaScript']);assert.deepEqual(validateProfile(m),[]);});
